# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Investing in Myself
tagline:          ''
description:      'My adventures as a Resident Apprentice at 8th Light.' 
url:              http://jakenations.me

author:
  name:           'Jake Nations'
  url:            https://twitter.com/nayshins

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/nayshins
